### ISSUE TITLE
Create a basic frontend

### ISSUE THREAD

**Issue by RiteshKSingh1709** [Shubham8287/flash#4]
- create one simple dropdown on writing it fetches data from api and show it to dropdown menu(for return can be any top k)
- On selection of particular value -> calls api to update the list
- or entering the new value will also calls update api 

React can be used here or even if simple jQuery, HTML,CSS.

@Shubham8287  any thoughts?

**Comment by Shubham8287** [comment]
Same I was thinking, looks good!

**Comment by RiteshKSingh1709** [comment]
Ok taking this one

**Comment by Shubham8287** [comment]
CORS is left here.

**Comment by RiteshKSingh1709** [comment]
closing this issue . already created issue for CORS - https://github.com/Shubham8287/flash/issues/16

**Comment by RiteshKSingh1709** [comment]
.
